### PR TITLE
21 launch error

### PR DESCRIPTION
**Pull request by Shivani-Chanda**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Dependencies

List any dependencies that are required for this change.

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration. (for bug fix / breaking change)
_Put an `x` in the boxes that apply_

- [x] Build Testing with `catkin build`
- [x] Simulation Testing
- [ ] Hardware Testing

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Shobuj-Paul** [comment]
Check if you're able to publish joint_values using RQT and give screenshot here.

**Comment by Shobuj-Paul** [comment]
Okay, nevermind just checked and it works
Put the same changes in the simulation package launch folder

**Comment by Shivani-Chanda** [comment]
Screenshot from 2023-01-29 15-12-23

**Comment by Shivani-Chanda** [comment]
same changes done in slambot_simulation.launch

**Review by Shobuj-Paul — APPROVED** [review]
Looks good to me.

**Pull request merged**
